# **Praktikum Kecerdasan Buatan - Post Test 7 - TensorFlow Basic**
###### Tjeng, Ivan Cahyadi 2009106146

## **Import Library**

In [2]:
import tensorflow as tf
import numpy as np

## **Random Tensor**

In [3]:
random_tensor = tf.random.normal([5,5], mean=0, stddev=1, seed=4)
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 0.29629603, -0.03141323, -0.05471061,  0.03763179,  2.564978  ],
       [-0.6494583 , -0.6845234 ,  0.43688074,  1.4897977 , -0.2399326 ],
       [ 0.04981674,  0.41748443,  0.11580934,  0.8780719 ,  0.27877015],
       [-1.5849335 ,  1.1436394 ,  1.0639356 ,  1.1304685 ,  1.3247743 ],
       [ 2.1117373 , -0.863544  , -1.8417858 ,  0.4749224 , -0.9902795 ]],
      dtype=float32)>

## **Prime Tensor**

In [4]:
primes = []

In [5]:
def is_prime (x):
  for i in range(2, x):
    if (x % i == 0):
      return False
  return True

In [6]:
row = []
number = 2

while (len(primes) < 5):
  while(len(row) < 5):
    if (is_prime(number)):
      row.append(number)
    number += 1
  primes.append(row)
  row = []

In [7]:
prime_tensor = tf.convert_to_tensor(primes, dtype=tf.float32)
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)>

## **Tensor Dimension**

In [8]:
random_tensor.shape

TensorShape([5, 5])

In [9]:
prime_tensor.shape

TensorShape([5, 5])

## **Arithmetic Operations**

In [10]:
tf.add(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.2962961,  2.9685867,  4.9452896,  7.037632 , 13.564978 ],
       [12.350542 , 16.315477 , 19.43688  , 24.489798 , 28.760067 ],
       [31.049816 , 37.417484 , 41.11581  , 43.87807  , 47.27877  ],
       [51.415066 , 60.14364  , 62.063934 , 68.13047  , 72.324776 ],
       [75.11174  , 78.13646  , 81.15821  , 89.47492  , 96.00972  ]],
      dtype=float32)>

In [11]:
tf.subtract(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ -1.703704 ,  -3.0314133,  -5.0547104,  -6.962368 ,  -8.435022 ],
       [-13.649458 , -17.684523 , -18.56312  , -21.510202 , -29.239933 ],
       [-30.950184 , -36.582516 , -40.88419  , -42.12193  , -46.72123  ],
       [-54.584934 , -57.85636  , -59.936066 , -65.86953  , -69.675224 ],
       [-70.88826  , -79.86354  , -84.84179  , -88.52508  , -97.99028  ]],
      dtype=float32)>

In [12]:
tf.multiply(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 5.9259206e-01, -9.4239704e-02, -2.7355304e-01,  2.6342255e-01,
         2.8214756e+01],
       [-8.4429579e+00, -1.1636898e+01,  8.3007336e+00,  3.4265347e+01,
        -6.9580455e+00],
       [ 1.5443188e+00,  1.5446924e+01,  4.7481828e+00,  3.7757092e+01,
         1.3102197e+01],
       [-8.4001480e+01,  6.7474724e+01,  6.4900070e+01,  7.5741386e+01,
         9.4058975e+01],
       [ 1.5415681e+02, -6.8219978e+01, -1.5286823e+02,  4.2268093e+01,
        -9.6057114e+01]], dtype=float32)>

In [13]:
tf.divide(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 0.14814802, -0.01047108, -0.01094212,  0.00537597,  0.23317981],
       [-0.04995833, -0.04026608,  0.02299372,  0.06477381, -0.00827354],
       [ 0.00160699,  0.01128336,  0.00282462,  0.02042028,  0.00593128],
       [-0.02990441,  0.01938372,  0.01744157,  0.01687266,  0.01865879],
       [ 0.02892791, -0.01093094, -0.02219019,  0.00533621, -0.01020907]],
      dtype=float32)>

In [14]:
tf.math.log(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-1.2163962 ,         nan,         nan, -3.279906  ,  0.94194984],
       [        nan,         nan, -0.828095  ,  0.39864033,         nan],
       [-2.9994044 , -0.87350804, -2.15581   , -0.13002677, -1.2773677 ],
       [        nan,  0.13421567,  0.06197489,  0.12263212,  0.28124207],
       [ 0.74751097,         nan,         nan, -0.7446039 ,         nan]],
      dtype=float32)>

In [15]:
tf.pow(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 8.7791339e-02, -3.0998308e-05, -4.9018240e-07,  1.0687699e-10,
         3.1616943e+04],
       [-3.6573492e-03, -1.5907470e-03,  1.4685713e-07,  9.5924150e+03,
        -1.0533880e-18],
       [ 0.0000000e+00,  9.1979401e-15,  0.0000000e+00,  3.7307271e-03,
         8.4445118e-27],
       [-3.9864439e+10,  2.7482639e+03,  4.3836586e+01,  3.7009812e+03,
         4.6997386e+08],
       [ 4.9970226e+23, -9.2570517e-06, -1.0347770e+22,  1.6573540e-29,
        -3.8770851e-01]], dtype=float32)>

checkpoint

## **Tensor Statistics Collection**

In [16]:
print(f'Nilai maksimal random_tensor: {tf.reduce_max(random_tensor).numpy()}',
      f'Nilai minimal  random_tensor: {tf.reduce_min(random_tensor).numpy()}',
      sep='\n' + '-'*50 + '\n')

Nilai maksimal random_tensor: 2.5649778842926025
--------------------------------------------------
Nilai minimal  random_tensor: -1.8417857885360718


## **Tensor Concatenation**

In [17]:
tf.concat([random_tensor, prime_tensor], axis=0)

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[ 2.9629603e-01, -3.1413235e-02, -5.4710608e-02,  3.7631791e-02,
         2.5649779e+00],
       [-6.4945829e-01, -6.8452340e-01,  4.3688074e-01,  1.4897977e+00,
        -2.3993260e-01],
       [ 4.9816735e-02,  4.1748443e-01,  1.1580934e-01,  8.7807190e-01,
         2.7877015e-01],
       [-1.5849335e+00,  1.1436394e+00,  1.0639356e+00,  1.1304685e+00,
         1.3247743e+00],
       [ 2.1117373e+00, -8.6354399e-01, -1.8417858e+00,  4.7492239e-01,
        -9.9027950e-01],
       [ 2.0000000e+00,  3.0000000e+00,  5.0000000e+00,  7.0000000e+00,
         1.1000000e+01],
       [ 1.3000000e+01,  1.7000000e+01,  1.9000000e+01,  2.3000000e+01,
         2.9000000e+01],
       [ 3.1000000e+01,  3.7000000e+01,  4.1000000e+01,  4.3000000e+01,
         4.7000000e+01],
       [ 5.3000000e+01,  5.9000000e+01,  6.1000000e+01,  6.7000000e+01,
         7.1000000e+01],
       [ 7.3000000e+01,  7.9000000e+01,  8.3000000e+01,  8.9000000e+01,
      

## **Tensor Sorting**

In [18]:
tf.sort(random_tensor, direction='DESCENDING')

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.564978  ,  0.29629603,  0.03763179, -0.03141323, -0.05471061],
       [ 1.4897977 ,  0.43688074, -0.2399326 , -0.6494583 , -0.6845234 ],
       [ 0.8780719 ,  0.41748443,  0.27877015,  0.11580934,  0.04981674],
       [ 1.3247743 ,  1.1436394 ,  1.1304685 ,  1.0639356 , -1.5849335 ],
       [ 2.1117373 ,  0.4749224 , -0.863544  , -0.9902795 , -1.8417858 ]],
      dtype=float32)>

In [26]:
tf.sort(prime_tensor, direction='DESCENDING')

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[11.,  7.,  5.,  3.,  2.],
       [29., 23., 19., 17., 13.],
       [47., 43., 41., 37., 31.],
       [71., 67., 61., 59., 53.],
       [97., 89., 83., 79., 73.]], dtype=float32)>